SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET collation_connection = utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `crm_transfer_detail`;
DROP TABLE IF EXISTS `crm_transfer_record`;
DROP TABLE IF EXISTS `crm_public_sea_rule`;
DROP TABLE IF EXISTS `crm_private_sea_config`;

CREATE TABLE IF NOT EXISTS `crm_private_sea_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `config_type` TINYINT NOT NULL DEFAULT 1 COMMENT '配置类型：1-全局配置, 2-角色配置, 3-用户配置',
    `role_id` BIGINT DEFAULT NULL COMMENT '角色ID',
    `role_name` VARCHAR(100) DEFAULT NULL COMMENT '角色名称',
    `user_id` BIGINT DEFAULT NULL COMMENT '用户ID',
    `user_name` VARCHAR(100) DEFAULT NULL COMMENT '用户姓名',
    `max_customer_count` INT NOT NULL DEFAULT 50 COMMENT '客户数量上限',
    `max_lead_count` INT NOT NULL DEFAULT 100 COMMENT '线索数量上限',
    `auto_recycle_days` INT NOT NULL DEFAULT 30 COMMENT '自动回收天数',
    `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：0-禁用, 1-启用',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '配置说明',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除：0-未删除 1-已删除',
    `create_by` VARCHAR(50) DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` VARCHAR(50) DEFAULT NULL,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `ext1` VARCHAR(255) DEFAULT NULL,
    `ext2` VARCHAR(255) DEFAULT NULL,
    `ext3` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_config_type` (`config_type`),
    KEY `idx_role_id` (`role_id`),
    KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='私海配置表';

CREATE TABLE IF NOT EXISTS `crm_public_sea_rule` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `rule_name` VARCHAR(100) NOT NULL COMMENT '规则名称',
    `rule_type` TINYINT NOT NULL DEFAULT 1 COMMENT '规则类型：1-先抢先得, 2-定期轮换',
    `rotate_days` INT DEFAULT 7 COMMENT '轮换天数',
    `claim_limit_per_day` INT NOT NULL DEFAULT 10 COMMENT '每日认领上限',
    `claim_limit_per_week` INT NOT NULL DEFAULT 50 COMMENT '每周认领上限',
    `auto_recycle_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用自动回收',
    `auto_recycle_days` INT NOT NULL DEFAULT 30 COMMENT '自动回收天数',
    `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：0-禁用, 1-启用',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '规则说明',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除：0-未删除 1-已删除',
    `create_by` VARCHAR(50) DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` VARCHAR(50) DEFAULT NULL,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `ext1` VARCHAR(255) DEFAULT NULL,
    `ext2` VARCHAR(255) DEFAULT NULL,
    `ext3` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公海规则配置表';

CREATE TABLE IF NOT EXISTS `crm_transfer_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `transfer_no` VARCHAR(50) NOT NULL COMMENT '转移单号',
    `transfer_type` TINYINT NOT NULL DEFAULT 1 COMMENT '转移类型：1-离职回收, 2-手动转移, 3-自动回收, 4-调岗转移',
    `transfer_type_name` VARCHAR(50) DEFAULT NULL COMMENT '转移类型名称',
    `from_user_id` BIGINT NOT NULL COMMENT '原负责人ID',
    `from_user_name` VARCHAR(100) NOT NULL COMMENT '原负责人姓名',
    `from_department_id` BIGINT DEFAULT NULL COMMENT '原部门ID',
    `from_department_name` VARCHAR(100) DEFAULT NULL COMMENT '原部门名称',
    `to_user_id` BIGINT DEFAULT NULL COMMENT '接手人ID',
    `to_user_name` VARCHAR(100) DEFAULT NULL COMMENT '接手人姓名',
    `to_department_id` BIGINT DEFAULT NULL COMMENT '目标部门ID',
    `to_department_name` VARCHAR(100) DEFAULT NULL COMMENT '目标部门名称',
    `transfer_method` TINYINT NOT NULL DEFAULT 1 COMMENT '转移方式：1-全部转移, 2-部分转移, 3-移入公海',
    `customer_count` INT NOT NULL DEFAULT 0 COMMENT '转移客户数量',
    `lead_count` INT NOT NULL DEFAULT 0 COMMENT '转移线索数量',
    `contract_count` INT NOT NULL DEFAULT 0 COMMENT '转移合同数量',
    `follow_count` INT NOT NULL DEFAULT 0 COMMENT '转移跟进记录数量',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-待确认, 1-已完成, 2-已取消',
    `reason` VARCHAR(500) DEFAULT NULL COMMENT '转移原因',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `operator_id` BIGINT NOT NULL COMMENT '操作人ID',
    `operator_name` VARCHAR(100) NOT NULL COMMENT '操作人姓名',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除：0-未删除 1-已删除',
    `create_by` VARCHAR(50) DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` VARCHAR(50) DEFAULT NULL,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `ext1` VARCHAR(255) DEFAULT NULL,
    `ext2` VARCHAR(255) DEFAULT NULL,
    `ext3` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_transfer_no` (`transfer_no`),
    KEY `idx_from_user_id` (`from_user_id`),
    KEY `idx_to_user_id` (`to_user_id`),
    KEY `idx_transfer_type` (`transfer_type`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源转移记录表';

CREATE TABLE IF NOT EXISTS `crm_transfer_detail` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `record_id` BIGINT NOT NULL COMMENT '转移记录ID',
    `transfer_no` VARCHAR(50) DEFAULT NULL COMMENT '转移单号',
    `resource_type` TINYINT NOT NULL COMMENT '资源类型：1-客户, 2-线索, 3-合同, 4-跟进记录',
    `resource_type_name` VARCHAR(50) DEFAULT NULL COMMENT '资源类型名称',
    `resource_id` BIGINT NOT NULL COMMENT '资源ID',
    `resource_no` VARCHAR(50) DEFAULT NULL COMMENT '资源编号',
    `resource_name` VARCHAR(200) DEFAULT NULL COMMENT '资源名称',
    `from_user_id` BIGINT NOT NULL COMMENT '原负责人ID',
    `from_user_name` VARCHAR(100) DEFAULT NULL COMMENT '原负责人姓名',
    `to_user_id` BIGINT DEFAULT NULL COMMENT '接手人ID',
    `to_user_name` VARCHAR(100) DEFAULT NULL COMMENT '接手人姓名',
    `transfer_status` TINYINT DEFAULT 1 COMMENT '转移状态：1-已转移, 2-已回收',
    `transfer_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '转移时间',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除：0-未删除 1-已删除',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_record_id` (`record_id`),
    KEY `idx_transfer_no` (`transfer_no`),
    KEY `idx_resource_type` (`resource_type`),
    KEY `idx_resource_id` (`resource_id`),
    KEY `idx_from_user_id` (`from_user_id`),
    KEY `idx_to_user_id` (`to_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源转移明细表';
